site_name: AWS Cloud Practitioner Notes
site_url: https://jalando-code.github.io/aws-notes/
site_author: Alba | @jalando.code
site_description: Apuntes visuales del curso AWS Cloud Practitioner â˜ï¸

theme:
  name: material
  logo: images/icons/favicon.png
  favicon: images/icons/favicon.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - search.highlight


extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jalando.code
      name: \@jalando.code
    - icon: fontawesome/brands/github
      link: https://github.com/albamdls
      name: albamdls

nav:
  - ğŸ  Home: index.md
  - â˜ï¸ AWS Cloud Practitioner:
      - ğŸ“Œ Module 1: cloud-practitioner/module_1.md
      - ğŸ“Œ Module 2: cloud-practitioner/module_2.md
      - ğŸ“Œ Module 3: cloud-practitioner/module_3.md
      - ğŸ“Œ Module 4: cloud-practitioner/module_4.md
      - ğŸ“Œ Module 5: cloud-practitioner/module_5.md
      - ğŸ“Œ Module 6: cloud-practitioner/module_6.md
      - ğŸ“Œ Module 7: cloud-practitioner/module_7.md
      - ğŸ“Œ Module 8: cloud-practitioner/module_8.md
      - ğŸ“Œ Module 9: cloud-practitioner/module_9.md
      - ğŸ“Œ Module 10: cloud-practitioner/module_10.md
  - ğŸ¤– AWS AI Practitioner:
      - ğŸ“Œ Module 1: ai-practitioner/module_1.md
      - ğŸ“Œ Module 2: ai-practitioner/module_2.md
      - ğŸ“Œ Module 3: ai-practitioner/module_3.md
      - ğŸ“Œ Module 4: ai-practitioner/module_4.md
      - ğŸ“Œ Module 5: ai-practitioner/module_5.md
      - ğŸ“Œ Module 6: ai-practitioner/module_6.md
      - ğŸ“Œ Module 7: ai-practitioner/module_7.md
      - ğŸ“Œ Module 8: ai-practitioner/module_8.md
